import type { Agent } from '@/types/walkinFormTypes';

export const JBR_ALL_AGENTS: Agent[] = [
    { id: "9846", name: "Tomas Plotegher" },
    { id: "9847", name: "Irene Gonzalez Cruz" },
    { id: "9848", name: "Rayyan Khan Kamran Khan" },
    { id: "9849", name: "Tamer Sameer Shaaban Hatuqai" },
    { id: "9850", name: "Brijeshkumar Virendrakumar Sharma" },
    { id: "9851", name: "Omayma El Alaoui Mrani" },
    { id: "9852", name: "Akshay Ashok Ashok Kumar" },
    { id: "9853", name: "Mir Zainulabedin Ali Ali Mir Yusuf" },
    { id: "9854", name: "Nitish Virendra Modi Virendra Pranlal Modi" },
    { id: "9855", name: "Fikir Habesha Moges" },
    { id: "9856", name: "Anton Ugrozov" },
    { id: "9857", name: "Abdullah Haitham Raja Aqel" },
    { id: "9858", name: "Cemile Atilan" },
    { id: "7133", name: "Sima Karia" },
    { id: "9816", name: "Himanshu Pandey Ashok Pandey" },
    { id: "9812", name: "Kamel Sameer Kamel Alhijawi" },
    { id: "6836", name: "Ferial Fortune" },
    { id: "7062", name: "Burak Han Karayaka" },
    { id: "6998", name: "Hajar Ez Zkak" },
    { id: "6847", name: "Asmara Dilara Sayim" },
    { id: "6883", name: "Prisca Elodie Marie Ertus" },
    { id: "7063", name: "Sanna Dahmani" },
    { id: "6999", name: "Safae Jamai Adib" },
    { id: "7170", name: "Felicia Sjåstad Hoftvedt" },
    { id: "7173", name: "Ailen Quindimil" },
    { id: "6991", name: "Nazer Sarkis" },
    { id: "9746", name: "Salim Mikram" },
    { id: "6217", name: "Lydia Ainouz" },
    { id: "9777", name: "Paula Civerchia" },
    { id: "9794", name: "Lahcene Messaoudene" },
    { id: "9792", name: "Anna Lethycia Franca Araujo" },
    { id: "9808", name: "Ivan Perez Sanchez" },
    { id: "9820", name: "Carlos Alberto Ruiz Guzman" },
    { id: "9821", name: "Aaron Omar Sosa" },
    { id: "7001", name: "Ghalid si Boukaceme" },
    { id: "7028", name: "Khaled Ibrahim" },
    { id: "7113", name: "Susan Baluch" },
    { id: "7111", name: "Rashda Bibi Hussain" },
    { id: "7140", name: "Osama Rashad Mohammad Abdel Hafez" },
    { id: "7139", name: "Hameda El Aouaji" },
    { id: "7000", name: "Ashraf Guennoun" },
    { id: "7184", name: "Zijaad Ghazal" },
    { id: "7185", name: "Julia Betsaida Labarta Serna" },
    { id: "7186", name: "Romy Drost" },
    { id: "7187", name: "Mohamad Alhaj Mohamad" },
    { id: "7075", name: "Oguzhan Akbas" },
    { id: "7189", name: "Sahar Puyan" },
    { id: "7199", name: "Sharief Stefan De Meza" },
    { id: "9759", name: "Roxy Schaap" },
    { id: "9760", name: "Sana Moenilal" },
    { id: "9761", name: "Marcel Dijkslag" },
    { id: "9762", name: "Germaine Janse" },
    { id: "9763", name: "Serap Tepe" },
    { id: "9764", name: "Sabine van Hoeij" },
    { id: "9765", name: "Pascal De Bruijn" },
    { id: "9766", name: "Rene Dowert" },
    { id: "9838", name: "Yelyzaveta Naumenko" },
    { id: "9839", name: "Sander Laurens Vogelaar" },
    { id: "9840", name: "Naima El Ouardani" },
    { id: "9841", name: "Farouk Jomaa N. Ben Ali" },
    { id: "9842", name: "Mariam Belkheir" },
    { id: "7153", name: "Bernd Schulze" },
    { id: "7156", name: "George Sebastian Hillard Hartley" },
    { id: "7155", name: "Inna Schulze" },
    { id: "7200", name: "Harro Lesch" },
    { id: "9775", name: "Timo Robert Lutz" },
    { id: "9799", name: "Steva Tomici" },
    { id: "9843", name: "Oleg Mudrak" },
    { id: "9844", name: "Miguel Zimmermann Vaz Sarafana" },
    { id: "9833", name: "Ehab Ali Alkanakri" },
    { id: "9822", name: "Rasha Walid Abdelghaffar Besheir Gawish" },
    { id: "9823", name: "Brunilda Hoxha" },
    { id: "9824", name: "Muhammad Aamir Saleem Nawab" },
    { id: "9825", name: "Syed Hamza Rizwan Syed Rizwan" },
    { id: "9826", name: "Anaya Kavi Jumani Kavi Ranchor Jumani" },
    { id: "9827", name: "Zainab Ali Abdulhussein Almaliki" },
    { id: "9828", name: "Lana Farid S Kawash" },
    { id: "9829", name: "Lazhar Boukhobza" },
    { id: "9830", name: "Ichrak Harabi" },
    { id: "9831", name: "Corrina Sandra Ford" },

    { id: "9809", name: "Khalfan Ali Khalfan Bin Ghuaifa Almansoori" },
    { id: "9810", name: "Laith Yousef M. Dababneh" },
    { id: "9811", name: "Sultan Hamad Ahmad Bin Sh Mejren Almarar" },
    { id: "9813", name: "Nahla Ahmed Mohamed Rabie Elkadi" },
    { id: "9814", name: "Saad Allah M Nabil Ghrewati" },
    { id: "9815", name: "Hamzah Mohammad Suliman Kullab" },

    { id: "6190", name: "Hassan Al Ahmad" },
    { id: "9749", name: "Ahmad Mufid R Ismail" },
    { id: "9758", name: "Joseph Antoine Ojeil" },
    { id: "9750", name: "Mohamed Amged Abdelraouf Awad Elsayed" },
    { id: "9751", name: "Nirav Harishkumar Dattani Harishkumar Lalsi Dattani" },
    { id: "9752", name: "Zeina Nidal Jaliko" },
    { id: "9753", name: "Strahinja Bogdanovic" },
    { id: "9755", name: "Mostafa Gaber Tawfik Abdelmotleb" },
    { id: "9757", name: "Yazan Ghaleb Mufadi Mousa" },
    { id: "6169", name: "Alexia Degas" },
    { id: "7168", name: "Scott Mason" },
    { id: "7169", name: "Santino Palmisano" },
    { id: "7171", name: "Nikhil Arora" },
    { id: "7172", name: "Matthew Craig Boswell" },
    { id: "7174", name: "Sameer Usman Mavadia Usman Ismail Mavadia" },
    { id: "7175", name: "Paula De Aguinaga Garcia" },
    { id: "7177", name: "Mariam Moheyaldin Mahmoud Abozeid" },
    { id: "7179", name: "Rakhaf Khassan" },

    { id: "7145", name: "Mohamed Samir Awad Awad Zoarob" },
    { id: "7146", name: "Mohamed AlSayed Abdelbadie Abdelnaby" },
    { id: "7148", name: "Hani AlAita" },
    { id: "7149", name: "Mohammad Bashar AL Nabblsi" },
    { id: "7150", name: "Waqar Javed Joseph Javed" },
    { id: "7151", name: "Nadine Chawki Halabi" },

    { id: "7112", name: "Jemaycia Brigitte Laisina" },
    { id: "7114", name: "Olga Olegovna Moreva" },
    { id: "7115", name: "Cajeda Bibi Hussain" },
    { id: "7116", name: "Mohammed Ibrahim" },
    { id: "7117", name: "Reshma Sharina Tewarie" },
    { id: "7119", name: "Nadine Hesham Ahmed Fouad Ali Yakout" },

    { id: "7121", name: "Hisham Husam M.S Daoud" },
    { id: "7122", name: "Anouar Amine Chabane" },
    { id: "7125", name: "Diana Estela Mendoza Sanchez" },

    { id: "7104", name: "Hala Ramzi Mohamad Ghazi" },
    { id: "7107", name: "Qusai Zaid Mohammad Alkhalaileh" },
    { id: "7099", name: "Gustavo Adolfo Chirinos Orihuela" },
    { id: "7100", name: "Marwa Amdouni" },
    { id: "7101", name: "Tibusiso Sibane Dlamini" },
    { id: "7102", name: "Andreea-Geanina Axinte" },
    { id: "7103", name: "Youssef Abdelmoneim Mahmoud Ahmed" },
    { id: "7105", name: "Basam Mala" },
    { id: "7106", name: "Rita Nejat Fahmi" },
    { id: "6992", name: "Elian Houssam Elkakhi" },
    { id: "6966", name: "Lina Mohd Mousa Alsahouri" },

    { id: "7091", name: "Sultan Mansoor Ahmad Bin Ghalaita Almheiri" },
    { id: "7092", name: "Ruaa Adnan Mohammed Saeed Al-Ani" },
    { id: "7093", name: "Saif Mohamed Malalla Abdelrahman Mohamed" },
    { id: "7094", name: "Mary Ghazi Elias" },
    { id: "7095", name: "Rameshwar Khude Rajaram Sopanrao Khude" },

    { id: "7079", name: "Gabriela Romana Bargan" },
    { id: "7080", name: "Noemi Raimondo" },
    { id: "7081", name: "Amene Taghi Daghayeghi" },
    { id: "7082", name: "Hussam Mohammad Beydoun" },
    { id: "7083", name: "Mohamed Shaban Mohamed Elghamry" },
    { id: "7084", name: "Hamdo Mohammad Samir Aldery" },
    { id: "7085", name: "Aafaf El Ammouri" },
    { id: "7086", name: "Katsiaryna Kuchkarava" },
    { id: "7074", name: "Alaa Mohamed Khamis Ahmed Moustafa" },
    { id: "7053", name: "Hanane Ettaziti" },
    { id: "7058", name: "Ibrahim Ziyad Halabi" },
    { id: "7059", name: "Abdulwahab Alhoumsi Altawil" },
    { id: "7060", name: "Charles William Prest James" },
    { id: "7061", name: "Nigar Muslum Qizi Ibrahim" },
    { id: "7064", name: "Komeyl Mirarabrazi" },
    { id: "4674", name: "Maisara Mohamed Fathy Ibrahim" },
    { id: "6693", name: "Ahmad Mohammad Ali Bazzari" },
    { id: "6669", name: "Rawaa Hassan A. Alrahmo Aljazzar" },
    { id: "6715", name: "Moahmed Abdelmonem Elsayed Abdalla Hassan" },
    { id: "4980", name: "Abdelhalim Almashni" },
    { id: "4518", name: "Shruq Zaid Mohammad" },
    { id: "4558", name: "Mohamed Elsayed Kamal Elmaghraby" },
    { id: "4799", name: "Mohamad Tawfiq Yousef Barakat" },
    { id: "4750", name: "Bassam Mohamed Mostafa" },
    { id: "4739", name: "Mohammad Samir A. Almashni" },
    { id: "6764", name: "Abdullah Amer Said Zain Al Abdeen" },
    { id: "5077", name: "Marwa Mohammad Al Koumi" },
    { id: "4883", name: "Anjuma Noor" },
    { id: "4884", name: "Mohammed Fahim Mohammed Forkan Alam" },
    { id: "6778", name: "Sara Marwan Al Moghrabi" },
    { id: "6833", name: "Dania Rasem Abdel Latif Watad" },
    { id: "6864", name: "Mohamed El Arbi Ben Chaabane" },
    { id: "6898", name: "Amin Salih Mustafa Ekasheh" },
    { id: "6326", name: "Mo'ath Mowafaq Said Zein Alabdin" },
    { id: "6930", name: "Khaldoun Hejazi Molakb Lahlh" },
    { id: "6950", name: "Ghaith Badir Ahmed Abdalla Almusharrekh" },
    { id: "6962", name: "Abdul Rahman Muhsen Hejazi" },
    { id: "4560", name: "Basma Mebarka" },
    { id: "4508", name: "Milana Albagachiyeva" },
    { id: "4403", name: "Ahmad Abdelqader Al Najjar" },
    { id: "6553", name: "Emad Jamal Abdalqader Abufazaa" },
    { id: "5037", name: "Basil Al Hourani" },
    { id: "4752", name: "Mahmoud Mohamed Farghaly" },
    { id: "6964", name: "Mohamed El Amine Takarli" },
    { id: "6352", name: "Ahmed Majed Ahmed Sabha" },
    { id: "6354", name: "Hina Balraj Singh" },
    { id: "6712", name: "Omar Mohamad Amer Khabazi" },
    { id: "6730", name: "Murat Ercemal" },
    { id: "4741", name: "Eda Beyza Yazici" },
    { id: "4598", name: "Ihab Bitar" },
    { id: "4746", name: "Shamuhammet Mossyyev" },
    { id: "6394", name: "Mehmet Ulas" },
    { id: "6925", name: "Saeed Bou Ghannam" },
    { id: "6926", name: "Asgad Osman Ezzaldeen Mohammedfarah" },
    { id: "4600", name: "Omar Ahmad Sa'ed Alqaraleh" },
    { id: "6947", name: "Mhd Nader Fouad Alchati" },
    { id: "6951", name: "Souzan Alaaeddin Ajjoum" },
    { id: "6963", name: "Diana Omar Abed El Khalek" },
    { id: "6958", name: "Hamad Yousuf Mohammad Yousuf Allanjawi" },
    { id: "6969", name: "Ayman Hikmat Mallak" },
    { id: "6975", name: "Charbel Maroun Bader" },
    { id: "6318", name: "Yaser Abdullah Saleh Khalil" },
    // ⬇️ continue adding the remaining agents here
];
